name: Build and Push Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
# Step 1: Checkout the code
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
# Step 2: Log in to GHCR
    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
# Step 3: Build and Push Image to GHCR
    - name: Build and Push Image
      run: |
        USERNAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$USERNAME/bship-soundwave:latest .
        docker push ghcr.io/$USERNAME/bship-soundwave:latest