name: Build and Push Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - name: Run Tests
        run: GO111MODULE=on go test ./...
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
# Step 1: Checkout the code
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
# Step 2: Log in to GHCR
    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
# Step 3: Build and Push Image to GHCR
    - name: Build and Push Image
      run: |
        USERNAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)  # Shorten SHA to 7 characters
        docker build -t ghcr.io/$USERNAME/bship-soundwave:latest -t ghcr.io/$USERNAME/bship-soundwave:$COMMIT_SHA .
        docker push ghcr.io/$USERNAME/bship-soundwave:latest
        docker push ghcr.io/$USERNAME/bship-soundwave:$COMMIT_SHA
# Step 4: Set up Google Cloud Auth
    - name: Set up Google Cloud Auth
      uses: google-github-actions/auth@v2
      with:
        project_id: operating-ethos-445009-n6
        credentials_json: ${{ secrets.GCP_SA_KEY }}

# Step 5: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: operating-ethos-445009-n6

# Step 5.5: Authenticate kubectl with GKE
    - name: Install Authenticator
      run: gcloud components install gke-gcloud-auth-plugin

# Step 6: Authenticate kubectl with GKE
    - name: Authenticate kubectl
      run: gcloud container clusters get-credentials bship-cluster --zone europe-west1-b --project operating-ethos-445009-n6

# Step 7: Deploy to GKE
    - name: Deploy to GKE
      run: |
        USERNAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)  # Shorten SHA to 7 characters
        kubectl set image deployment/backend-soundwave \
          bship-soundwave=ghcr.io/$USERNAME/bship-soundwave:$COMMIT_SHA
        kubectl rollout status deployment/backend-soundwave